UI-MVC/Areas/Scholen/Pages/Scholen.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ST.BL.Domain.Identity;
using ST.BL.Domain.Scholen;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Scholen.Pages
{
    public class Scholen : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IGebruikerManager _gebruikerManager;
        private readonly ISchoolManager _schoolManager;

        [BindProperty] public InputModel Input { get; set; }
        public string ReturnUrl { get; set; }


        public class InputModel
        {
            public List<DetailsSchool> DetailsSchool { get; set; }
        }

        public class DetailsSchool
        {
            public School School { get; set; }
            public int AantalGebruikers { get; set; }
            public int AantalTesten { get; set; }
            public bool IsChecked { get; set; }
        }


        public Scholen(
            UserManager<ApplicationUser> userManager,
            IGebruikerManager gebruikerManager, ISchoolManager schoolManager
        )
        {
            _userManager = userManager;
            _gebruikerManager = gebruikerManager;
            _schoolManager = schoolManager;
        }


        public async Task OnGet(string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }
            ReturnUrl = returnUrl;
            Input = new InputModel();
            Input.DetailsSchool = new List<DetailsSchool>();

            var scholen = _schoolManager.GetScholen();
            var alleGebruikers = _gebruikerManager.GetGebruikers().ToList();
            var usersInRole = await _userManager.GetUsersInRoleAsync("RegisteredUser");
            foreach (var school1 in scholen)
            {
                DetailsSchool detailsSchool = new DetailsSchool();
                // je zet alle identity leerkrachten om naar gebruiker leerkrachten
                var gebruikers = new List<ST.BL.Domain.Users.Gebruiker>();
                foreach (var geb in usersInRole.ToList())
                {
                    var a = alleGebruikers.Find(g => g.Username.ToLower().Equals(geb.UserName.ToLower()));
                    gebruikers.Add(a);
                }

                // je zoekt hoeveel van die gebruiker leerkrachten in de school aanwezig zijn
                var chosen = new List<ST.BL.Domain.Users.Gebruiker>();
                foreach (var geb in gebruikers)
                {
                    if (school1.Gebruikers.Contains(geb))
                    {
                        chosen.Add(geb);
                    }
                }

                detailsSchool.School = school1;
                detailsSchool.AantalGebruikers = chosen.Count;
                Input.DetailsSchool.Add(detailsSchool);
            }
        }

        public IActionResult OnPostDeleteSchool(int[] cb)
        {
        
            var ids = cb;
            var verwijderenScholen = _schoolManager.GetScholen().Where(s => ids.Contains(s.Id)).ToList();
            foreach (var school in verwijderenScholen)
            {
                var opgehaaldeSchool = _schoolManager.GetSchoolById(school.Id);
                _schoolManager.RemoveSchool(opgehaaldeSchool);
            }

            return LocalRedirect("/Scholen/Scholen");
        }
    }
}

UI-MVC/Areas/Spellen/Pages/AddSpel.cshtml.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ST.BL.Domain;
using ST.BL.Domain.Antwoorden;
using ST.BL.Domain.Identity;
using ST.BL.Domain.InternMediateClasses;
using ST.BL.Domain.Spellen;
using ST.BL.Domain.Stellingen;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Spellen.Pages
{
    public class AddSpel : PageModel
    {
        private readonly IGebruikerStellingenManager _gebruikerStellingenManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IGebruikerManager _gebruikerManager;
        private readonly IStellingManager _stellingManager;
        private readonly ISpelManager _spelManager;
        private readonly IKlasSpellenManager _klasSpellenManager;
        private readonly ISpelStellingenManager _spelStellingenManager;

        public AddSpel(
            IGebruikerStellingenManager gebruikerStellingenManager,
            UserManager<ApplicationUser> userManager,
            IGebruikerManager gebruikerManager,
            IStellingManager stellingManager,
            ISpelManager spelManager,
            IKlasSpellenManager klasSpellenManager,
            ISpelStellingenManager spelStellingenManager
        )
        {
            _gebruikerStellingenManager = gebruikerStellingenManager;
            _userManager = userManager;
            _gebruikerManager = gebruikerManager;
            _stellingManager = stellingManager;
            _spelManager = spelManager;
            _klasSpellenManager = klasSpellenManager;
            _spelStellingenManager = spelStellingenManager;
        }

        [BindProperty] public int KlasId { get; set; }
        [BindProperty] public int SpelId { get; set; }
        [BindProperty] public AddSpelModel Input { get; set; }
        [BindProperty] public SettingsModel SettingsInput { get; set; }
        [BindProperty] public Spel Spel { get; set; }

        [BindProperty] public bool IsPartijSpel { get; set; }

        // public List<List<GebruikerStellingen>> SortedByThemaStellingen { get; set; }
        // [BindProperty] public bool Result { get; set; }

        public class SettingsModel
        {
            public string Name { get; set; }

            [Display(Name = "Color The Screen Post Answer")]
            public bool ColorScreenPostAnswer { get; set; }

            [Display(Name = "Allow Argument Input")]
            public bool AllowArgumentInput { get; set; }

            [Display(Name = "Explain Difficult Words")]
            public bool ExplainDifficultWord { get; set; }

            [Display(Name = "Skip Questions")] public bool Skip { get; set; }
            public Status Status { get; set; }
        }


        public class AddSpelModel
        {
            public AddSpelModel()
            {
                GebruikerStellingen = new List<GebruikerStellingen>();
            }

            public List<GebruikerStellingen> GebruikerStellingen { get; set; }
            public List<int> areChecked { get; set; }
        }

        public string ReturnUrl { get; set; }

        public async Task OnGet(int klasId, int spelId = 0, string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                var index = returnUrl.Split('1');
                returnUrl = $"~/{index[1].Substring(1)}";
            }

            ReturnUrl = returnUrl;

            KlasId = klasId;
            SpelId = spelId;

            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);

            Input = new AddSpelModel
            {
                GebruikerStellingen = _gebruikerStellingenManager
                    .GetGebruikerStellingen()
                    .Where(g => g.GebruikerId == gebruiker.Id)
                    .ToList()
            };
            
            
            
        }

        // public int SessieId { get; set; }

        public IActionResult OnPostSelectStelling(int spelId, string returnUrl = null)
        {
            ReturnUrl = returnUrl;
        
            var x = _spelStellingenManager.GetSpelStellingen().Where(s => s.SpelId == spelId).ToList();
            foreach (var spelStellingen in x)
            {
                spelStellingen.Selected = false;
            }
        
            foreach (var stelling in Input.areChecked.Select(i => _stellingManager.GetStellingById(i)))
            {
                var found = _spelStellingenManager.GetSpelStellingen().Where(s => s.StellingId == stelling.Id)
                    .SingleOrDefault(s => s.SpelId == spelId);
                if (found == null)
                {
                    _spelStellingenManager.AddSpelStelling(new SpelStellingen
                        {SpelId = spelId, StellingId = stelling.Id, Selected = true});
                }
                else
                {
                    found.Selected = true;
                    _spelStellingenManager.ChangeSpelStelling(found);
                }
            }
            return LocalRedirect(returnUrl);
        }

        public IActionResult OnPostCreateStelling(int klasId, int spelId, string returnUrl = null)
        {
            var stelling = new Stelling
            {
                MoeilijkeWoorden = new List<MoeilijkWoord>(),
                PartijAntwoordOpStelling = new List<PartijAntwoordOpStelling>(),
                Status = Status.Pending,
                StellingOnderwerp = "",
                Uitleg = "",
                Vraag = "",
                UserAntwoordOpStelling = new List<UserAntwoordOpStelling>()
            };
            var result = _stellingManager.AddStelling(stelling);

            return RedirectToPage("/AddStelling",
                new {area = "Stellingen", klasId, spelId, stellingId = result.Id, returnUrl});
        }

        public async Task<IActionResult> OnPostCreateSpel(int klasId, string returnUrl = null)
        {
            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);

            var options = new Options()
            {
                ColorScreenPostAnswer = SettingsInput.ColorScreenPostAnswer,
                AllowArgumentInput = SettingsInput.AllowArgumentInput,
                ExplainDifficultWord = SettingsInput.ExplainDifficultWord,
                Skip = SettingsInput.Skip,
            };

            if (IsPartijSpel)
            {
                Spel = new PartijSpel()
                {
                    Name = SettingsInput.Name,
                    Status = SettingsInput.Status,
                    Creator = gebruiker,
                    options = options
                };
                Spel = (PartijSpel) _spelManager.AddSpel(Spel);
            }
            else
            {
                Spel = new DebatSpel()
                {
                    Name = SettingsInput.Name,
                    Status = SettingsInput.Status,
                    Creator = gebruiker,
                    options = options
                };
                Spel = (DebatSpel) _spelManager.AddSpel(Spel);
            }

            var ks = new KlasSpellen {KlasId = klasId, SpelId = Spel.SpelId};
            _klasSpellenManager.AddKlasSpel(ks);

            foreach (var stelling in Input.areChecked.Select(i => _stellingManager.GetStellingById(i)))
            {
                _spelStellingenManager.AddSpelStelling(new SpelStellingen
                {
                    SpelId = Spel.SpelId,
                    StellingId = stelling.Id,
                    Selected = true
                });
            }

            return RedirectToPage("/AddSessie", new {area = "Sessies", klasId = klasId});
        }
    }
}

UI-MVC/Areas/Spellen/Pages/DetailsSpel.cshtml.cs
using Microsoft.AspNetCore.Mvc.RazorPages;
using ST.BL.Domain.Spellen;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Spellen.Pages
{
    public class DetailsSpel : PageModel
    {
        private readonly ISpelManager _spelManager;
        public Spel Spel { get; set; }

        public DetailsSpel(ISpelManager spelManager)
        {
            _spelManager = spelManager;
        }
        
        public void OnGet(int spelId)
        {
            Spel = _spelManager.GetSpelById(spelId);
        }
    }
}

UI-MVC/Areas/Spellen/Pages/GetSpel.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ST.BL.Domain.Identity;
using ST.BL.Domain.Spellen;
using ST.BL.Domain.Stellingen;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Spellen.Pages
{
    public class GetSpel : PageModel
    {
        private readonly ISpelManager _spelManager;
        private readonly IStellingManager _stellingManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IGebruikerManager _gebruikerManager;

        [BindProperty] public InputModel Input { get; set; }
        public string ReturnUrl { get; set; }


        public class InputModel
        {
            public List<DetailsSpel> DetailsSpel { get; set; }
        }

        public class DetailsSpel
        {
            public Spel Spel { get; set; }
            public string School { get; set; }
            public string Eigenaar { get; set; }
            public int AantalStellingen { get; set; }
            public bool IsChecked { get; set; }
        }


        public GetSpel(
            ISpelManager spelManager,
            IStellingManager stellingManager, UserManager<ApplicationUser> userManager,
            IGebruikerManager gebruikerManager
        )
        {
            _spelManager = spelManager;
            _stellingManager = stellingManager;
            _userManager = userManager;
            _gebruikerManager = gebruikerManager;
        }


        public async Task OnGet(string returnUrl = null)
        {
            Input = new InputModel();
            Input.DetailsSpel = new List<DetailsSpel>();
            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);
            var spellen = _spelManager.GetSpellen().Where(s => s.Creator.Id == gebruiker.Id).ToList();
            var alleStellingen = _stellingManager.GetStellingen().ToList();
            foreach (var spel in spellen)
            {
                DetailsSpel detailsSpel = new DetailsSpel();
                var stellingen = new List<Stelling>();
                foreach (var stel in alleStellingen)
                {
                    if (spel.Stellingen.Contains(stel))
                    {
                        stellingen.Add(stel);
                    }
                }

                detailsSpel.Spel = spel;
                detailsSpel.AantalStellingen = stellingen.Count;
                detailsSpel.Eigenaar = spel.Creator.Username;
                detailsSpel.School = spel.Creator.School.Naam;
                Input.DetailsSpel.Add(detailsSpel);
            }
        }

        public IActionResult OnPostDeleteSpel(int[] cb)
        {
            var ids = cb;
            var verwijderenSpellen = _spelManager.GetSpellen().Where(s => ids.Contains(s.SpelId)).ToList();
            foreach (var spel in verwijderenSpellen)
            {
                var opgehaaldSpel = _spelManager.GetSpelById(spel.SpelId);
                _spelManager.RemoveSpel(opgehaaldSpel);
            }

            return LocalRedirect("/Spellen/GetSpel");
        }
    }
}

UI-MVC/Areas/Spellen/Pages/Spellen.cshtml.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using ST.BL.Domain.Identity;
using ST.BL.Domain.Scholen;
using ST.BL.Domain.Spellen;
using ST.BL.Domain.Stellingen;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Spellen.Pages
{
    public class Spellen : PageModel
    {
        private readonly ISpelManager _spelManager;
        private readonly IStellingManager _stellingManager;

        [BindProperty] public InputModel Input { get; set; }


        public class InputModel
        {
            public List<DetailsSpel> DetailsSpel { get; set; }
        }

        public class DetailsSpel
        {
            public Spel Spel { get; set; }
            public string School { get; set; }
            public string Eigenaar { get; set; }
            public int AantalStellingen { get; set; }
            public bool IsChecked { get; set; }
        }


        public Spellen(
            ISpelManager spelManager,
            IStellingManager stellingManager
        )
        {
            _spelManager = spelManager;
            _stellingManager = stellingManager;
        }


        public void OnGet()
        {
            Input = new InputModel();
            Input.DetailsSpel = new List<DetailsSpel>();

            var spellen = _spelManager.GetSpellen().ToList();
            var alleStellingen = _stellingManager.GetStellingen().ToList();
            foreach (var spel in spellen)
            {
                DetailsSpel detailsSpel = new DetailsSpel();
                var stellingen = new List<Stelling>();
                foreach (var stel in alleStellingen)
                {
                    if (spel.Stellingen.Contains(stel))
                    {
                        stellingen.Add(stel);
                    }
                }

                detailsSpel.Spel = spel;
                detailsSpel.AantalStellingen = stellingen.Count;
                detailsSpel.Eigenaar = spel.Creator.Username;
                detailsSpel.School = spel.Creator.School.Naam;
                Input.DetailsSpel.Add(detailsSpel);
            }
        }
    }
}

UI-MVC/Areas/Spellen/Pages/AddSpel.cshtml
@page
@using ST.BL.Domain
@using Microsoft.AspNetCore.Http.Extensions
@model UI_MVC.Areas.Spellen.Pages.AddSpel

@{
    Layout = "_Layout";
    var klasId = Model.KlasId;
    var gebruikerStellingen = Model.Input.GebruikerStellingen;

    var returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
    returnUrl = $"~/{returnUrl.Substring(23)}";
}
<input type="text" hidden value="@Model.KlasId" name="KlasId">
<input type="text" hidden value="@Model.SpelId" name="SpelId">
<br>
@* TODO: Select Stellingen Groep *@
<form method="post">
    <div class="d-flex flex-row">
        <div class="d-flex flex-column col-8">
            <div class="d-flex row justify-content-between align-items-center" style="padding: 0 15px;">
                <h2>Add Spel</h2>
                <a class="btn btn-primary" asp-area="Stellingen" asp-page="AddStelling" asp-route-klasId="@Model.KlasId">Create Stelling</a>
            </div>

            <div>
                <div class="jumbotron" style="padding: 1rem 2rem;">
                    <h5 style="text-align: center">Stellingen</h5>
                    @* TODO create stellingen *@
                    @*<input type="submit" class="btn btn-primary" asp-page-handler="CreateStelling" asp-route-klasId="@klasId" asp-route-SpelId="@spelId" asp-route-returnUrl="@returnUrl" value="Create New Stelling">*@
                    <div class="table-responsive">
                        <table class="table table-striped table-hover table-sm" style="text-align: center">
                            <thead class="thead-dark">
                            <tr>
                                <th scope="col">Onderwerp</th>
                                <th scope="col">Vraag</th>
                                <th scope="col">Select</th>
                            </tr>
                            </thead>
                            <tbody>
                            @foreach (var gb in gebruikerStellingen)
                            {
                                <tr>
                                    <th scope="row">@gb.Stelling.StellingOnderwerp</th>
                                    <td>@gb.Stelling.Vraag</td>
                                    <td>
                                        <div class="checkbox">
                                            @if (gebruikerStellingen.Find(s => s.StellingId == gb.StellingId) != null)
                                            {
                                                <input type="checkbox" name="areChecked" value="@gb.StellingId" checked="@gebruikerStellingen.Single(s => s.StellingId == gb.StellingId).Selected"/>
                                            }
                                            else
                                            {
                                                <input type="checkbox" name="areChecked" value="@gb.StellingId"/>
                                            }
                                        </div>
                                        @* <input type="checkbox" name="areChecked" value="@gb.StellingId"/> *@
                                    </td>
                                </tr>
                            }
                            </tbody>
                        </table>
                    </div>
                    <hr>
                    <div class="d-flex flex-row justify-content-center">
                        @* <input type="submit" value="Add Selected" class="btn btn-primary" style="width: 10rem;" asp-page="AddSpel" asp-page-handler="SelectStelling" asp-route-returnUrl="@returnUrl"> *@
                    </div>
                </div>
            </div>
        </div>
        <div class="col-4">
            <h2>Options</h2>
            <input type="button" style="margin-bottom: 3px" class="btn btn-dark" value="Import Stellingen"/>
            <div class="input-group">
                <div class="input-group-prepend">
                    <span class="input-group-text">Spel Name</span>
                </div>
                <input type="text" class="form-control" asp-for="SettingsInput.Name">
            </div>
            <br>
            <div class="checkbox">
                <label asp-for="SettingsInput.ColorScreenPostAnswer">
                    <input asp-for="SettingsInput.ColorScreenPostAnswer"/>
                    @Html.DisplayNameFor(m => m.SettingsInput.ColorScreenPostAnswer)
                </label>
            </div>
            <div class="checkbox">
                <label asp-for="SettingsInput.AllowArgumentInput">
                    <input asp-for="SettingsInput.AllowArgumentInput"/>
                    @Html.DisplayNameFor(m => m.SettingsInput.AllowArgumentInput)
                </label>
            </div>
            <div class="checkbox">
                <label asp-for="SettingsInput.ExplainDifficultWord">
                    <input asp-for="SettingsInput.ExplainDifficultWord"/>
                    @Html.DisplayNameFor(m => m.SettingsInput.ExplainDifficultWord)
                </label>
            </div>
            <div class="checkbox">
                <label asp-for="SettingsInput.Skip">
                    <input asp-for="SettingsInput.Skip"/>
                    @Html.DisplayNameFor(m => m.SettingsInput.Skip)
                </label>
            </div>
            <br>
            <div class="input-group" style="margin: 2px 0">
                <div class="input-group-prepend">
                    <span class="input-group-text">Status</span>
                </div>
                <select class="custom-select" asp-items="Html.GetEnumSelectList<Status>()" asp-for="SettingsInput.Status">
                </select>
            </div>
            <div class="input-group" style="margin: 2px 0">
                <div class="input-group-prepend">
                    <span class="input-group-text">Kind of Game</span>
                </div>
                <select class="custom-select" asp-for="IsPartijSpel">
                    <option value="true">Partijspel</option>
                    <option value="false">Debatspel</option>
                </select>
            </div>
        </div>
    </div>
    <hr>
    <div class="d-flex flex-row justify-content-center">
        <input style="margin: 2px" type="submit" class="btn btn-primary" asp-page-handler="CreateSpel" asp-route-klasId="@klasId" asp-route-returnUrl="@Model.ReturnUrl" value="Create Spel"/>
        <a style="margin: 2px" class="btn btn-secondary" asp-area="Sessies" asp-page="AddSessie" asp-route-klasId="@klasId">Cancel</a>
    </div>
</form>

UI-MVC/Areas/Spellen/Pages/DetailsSpel.cshtml
@page
@using ST.BL.Domain.InternMediateClasses
@model UI_MVC.Areas.Spellen.Pages.DetailsSpel

@{
    ViewData["Title"] = "Speloverzicht";
}

<h2>Details @Model.Spel.Name</h2>
<p>Created by <b>@Model.Spel.Creator.Voornaam @Model.Spel.Creator.Achternaam</b></p>

<h5>Stellingen</h5>
@foreach (SpelStellingen stelling in @Model.Spel.SpelStellingen)
{
    <p>@stelling.Stelling.Vraag</p>
}

UI-MVC/Areas/Spellen/Pages/GetSpel.cshtml
@page
@model UI_MVC.Areas.Spellen.Pages.GetSpel


@{
    ViewData["Title"] = "Spellenoverzicht";
    Layout = "_Layout";
}

@section Scripts
{
    <script type="module" src="~/dist/overview.entry.js" defer></script>
}
<link rel="stylesheet" href="~/dist/overview.css">

<div class="jumbotron">
    <div class="row kaartTop my-3 p-3 bg-white rounded box-shadow verticalalign">
        <div class="col-10">
            <h1 class="ha">Spellen</h1>
        </div>
        <div class="col-2">
            <a class="btn btn-primary" asp-area="Spellen" asp-page="/AddSpel">Nieuw spel Toevoegen</a>
        </div>
    </div>
    
    <div class="btn-group-justified float-left">
        <button class="btn btn-primary" id="checkAlles">Select All</button>
        <button class="btn btn-primary" id="checkNiets">Deselect All</button>
    </div>

    <form method="post">
        <div class="row">
            <div class="col-12 float-right">
                <input type="submit" class="btn btn-danger float-right" value="Verwijderen" asp-page-handler="DeleteSpel"/>
            </div>
        </div>
        
        @foreach (var spel in @Model.Input.DetailsSpel)
        {
            <div class="row my-3 p-3 bg-white rounded box-shadow verticalalign">
                <div class="col-1 text-center">
                    <label class="checkbox path">
                        <input type="checkbox" asp-for="@spel.IsChecked" name="cb" value="@spel.Spel.SpelId">
                        <svg viewBox="0 0 21 21">
                            <path d="M5,10.75 L8.5,14.25 L19.4,2.3 C18.8333333,1.43333333 18.0333333,1 17,1 L4,1 C2.35,1 1,2.35 1,4 L1,17 C1,18.65 2.35,20 4,20 L17,20 C18.65,20 20,18.65 20,17 L20,7.99769186"></path>
                        </svg>
                    </label>
                </div>
                <div class="col-10">
                    <p class="pe"><strong class="d-block">@spel.Spel.Name (@spel.Spel.SpelStellingen.Count stellingen)</strong> @spel.School, @spel.Eigenaar </p>
                </div>
                <div class="col-1">
                    <a asp-area="Spellen" asp-page="/DetailsSpel" asp-route-spelId="@spel.Spel.SpelId">
                        <svg height="50%" viewBox="0 0 16 16" fill="black" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
                        </svg>
                    </a>
                </div>
            </div>
        }
    </form>
</div>

UI-MVC/Areas/Spellen/Pages/SchoolSpel.cshtml
@page
@using Microsoft.AspNetCore.Http.Extensions
@model UI_MVC.Areas.Spellen.Pages.SchoolSpel
@{
    ViewData["Title"] = "spellen overzicht";
    Layout = "_Layout";

}

@section Scripts
{
    <script type="module" src="~/dist/overview.entry.js" defer></script>
}

<div class="row">
    <h1>Spellen van uw school</h1>
</div>
<div class="btn-group-justified">
    <a class="btn btn-primary" asp-area="Spellen" asp-page="/AddSpel" asp-route-returnUrl="@Model.ReturnUrl">Toevoegen</a>
    <a class="btn btn-primary" id="checkAlles">Select All</a>
    <a class="btn btn-primary" id="checkNiets">Deselect All</a>
</div>
<form method="post">
    <div class="row">
        <div class="col-8">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">SpelNaam</th>
                    <th scope="col">Aantal Stellingen</th>
                    <th scope="col">School</th>
                    <th scope="col">Eigenaar</th>
                    <th scope="col">Selecteren</th>
                    <th scope="col">Beheren</th>
                </tr>
                </thead>
                <tbody>

                @foreach (var spel in @Model.Input.DetailsSpel)
                {
                    <tr>
                        <td>@spel.Spel.Name</td>
                        <td>@spel.AantalStellingen</td>
                        <td>@spel.School</td>
                        <td>@spel.Eigenaar</td>
                        <td>
                            <input type="checkbox" asp-for="@spel.IsChecked" name="cb" value="@spel.Spel.SpelId"/>
                        </td>
                         <td> 
                             <a class="btn btn-primary" asp-area="Spellen" asp-page="/EditSpel" asp-route-id="@spel.Spel.SpelId" asp-route-returnUrl="@Model.ReturnUrl">Beheren</a> 
                         </td> 
                    </tr>
                }
                </tbody>
            </table>
        </div>
        <div class="col-4">
            <div class="row">
                <input type="submit" class="btn btn-primary" value="Verwijderen" asp-page-handler="DeleteSchool"/>
            </div>
        </div>
    </div>
</form>