UI-MVC/Areas/Gebruikers/Pages/EditGebruiker.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ST.BL.Domain.Identity;
using ST.BL.Interfaces;
using ST.DAL.Interfaces;

namespace UI_MVC.Areas.Gebruikers.Pages
{
    public class EditGebruiker : PageModel
    {
        private readonly ISchoolManager _schoolManager;

        private readonly IGebruikerManager _gebruikerManager;
        [BindProperty] public InputModel Input { get; set; }
        public string ReturnUrl { get; set; }

        public EditGebruiker(IGebruikerManager gebruikerManager,
            ISchoolManager schoolManager)
        {
            _gebruikerManager = gebruikerManager;
            _schoolManager = schoolManager;
        }

        public class InputModel
        {
            public int Id { get; set; }

            [Required]
            [Display(Name = "Username")]
            public string Username { get; set; }

            [Required]
            [Display(Name = "Voornaam")]
            public string Voornaam { get; set; }

            [Required]
            [Display(Name = "Achternaam")]
            public string Achternaam { get; set; }

            [Required] [Display(Name = "Email")] public string Email { get; set; }

            [Required] [Display(Name = "School")] public string School { get; set; }
            public int SchoolId { get; set; }
        }

        public void OnGet(int id, string returnUrl = null)
        {
            var gekozenGebruiker = _gebruikerManager.GetGebruikerById(id);
            Input = new InputModel
            {
                Id = id,
                Username = gekozenGebruiker.Username,
                Voornaam = gekozenGebruiker.Voornaam,
                Achternaam = gekozenGebruiker.Achternaam,
                Email = gekozenGebruiker.Email,
                School = gekozenGebruiker.School.Naam,
                SchoolId = gekozenGebruiker.School.Id
            };
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;
        }

        public IActionResult OnPostEditGebruiker(int id, string returnUrl = null)
        {
            var opgehaaldeGebruiker = _gebruikerManager.GetGebruikerById(id);
            opgehaaldeGebruiker.Username = Input.Username;
            opgehaaldeGebruiker.Voornaam = Input.Voornaam;
            opgehaaldeGebruiker.Achternaam = Input.Achternaam;
            opgehaaldeGebruiker.Email = Input.Email;
            opgehaaldeGebruiker.School = _schoolManager.GetScholen().Single(s => s.Naam.Equals(Input.School));
            _gebruikerManager.ChangeGebruiker(opgehaaldeGebruiker);

            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;
            return LocalRedirect(ReturnUrl);
        }
    }
}

UI-MVC/Areas/Gebruikers/Pages/Gebruikers.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ST.BL.Domain.Identity;
using ST.BL.Domain.Users;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Gebruikers.Pages
{
    public class Gebruikers : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IGebruikerManager _gebruikerManager;

        public Gebruikers(
            UserManager<ApplicationUser> userManager,
            IGebruikerManager gebruikerManager
        )
        {
            _userManager = userManager;
            _gebruikerManager = gebruikerManager;
        }

        [BindProperty] public InputModel Input { get; set; }

        public class InputModel
        {
            public List<DetailsLeerkracht> DetailsLeerkrachten { get; set; }
        }

        public string ReturnUrl { get; set; }
        public DetailsLeerkracht Leerkracht { get; set; }

        public class DetailsLeerkracht
        {
            public Gebruiker Leerkracht { get; set; }
            public bool IsChecked { get; set; }
        }

        public async Task OnGet(string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;

            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);
            var Leerkrachten = new List<Gebruiker>();

            Leerkrachten = _gebruikerManager
                .GetGebruikers()
                .ToList();
            foreach (var L in Leerkrachten)
            {
                DetailsLeerkracht detailsLeerkracht = new DetailsLeerkracht();
                detailsLeerkracht.Leerkracht = L;
                detailsLeerkracht.IsChecked = false;
                Input.DetailsLeerkrachten.Add(detailsLeerkracht);
            }
        }

        public IActionResult OnPostDeleteAsync(int[] cb, string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;

            var ids = cb;
            var verwijderenGebruiker = _gebruikerManager.GetGebruikers().Where(g => ids.Contains(g.Id)).ToList();
            foreach (var g in verwijderenGebruiker)
            {
                var opgehaaldeGebruiker = _gebruikerManager.GetGebruikerById(g.Id);
                _gebruikerManager.RemoveGebruiker(opgehaaldeGebruiker);
            }

            return LocalRedirect(ReturnUrl);
        }
    }
}

UI-MVC/Areas/Gebruikers/Pages/SchoolGebruikers.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ST.BL.Domain.Identity;
using ST.BL.Domain.Users;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Gebruikers.Pages
{
    public class SchoolGebruikers : PageModel
    {
        private readonly IGebruikerManager _gebruikerManager;
        private readonly UserManager<ApplicationUser> _userManager;


        public SchoolGebruikers(UserManager<ApplicationUser> userManager,
            IGebruikerManager gebruikerManager
        )
        {
            _userManager = userManager;
            _gebruikerManager = gebruikerManager;
        }

        [BindProperty] public InputModel Input { get; set; }

        public class InputModel
        {
            public List<DetailsLeerkracht> DetailsLeerkrachten { get; set; }
            public int SchoolId { get; set; }
        }

        public string ReturnUrl { get; set; }

        public class DetailsLeerkracht
        {
            public Gebruiker Leerkracht { get; set; }
            public bool IsChecked { get; set; }
        }

        public async Task OnGet(string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;
            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);

            Input = new InputModel();
            Input.SchoolId = gebruiker.School.Id;
            Input.DetailsLeerkrachten = new List<DetailsLeerkracht>();

            var alleGebruikers = _gebruikerManager.GetGebruikers().Where(g => g.School != null).ToList();

            foreach (var g in alleGebruikers)
            {
                if (g.School.Id.Equals(gebruiker.School.Id))
                {
                    DetailsLeerkracht detailsLeerkracht = new DetailsLeerkracht();
                    detailsLeerkracht.Leerkracht = g;
                    Input.DetailsLeerkrachten.Add(detailsLeerkracht);
                }
            }
        }

        public IActionResult OnPostDeleteGebruiker(int[] cb, string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;

            var ids = cb;
            var verwijderenGebruiker = _gebruikerManager.GetGebruikers().Where(g => ids.Contains(g.Id)).ToList();
            foreach (var g in verwijderenGebruiker)
            {
                var opgehaaldeGebruiker = _gebruikerManager.GetGebruikerById(g.Id);
                _gebruikerManager.RemoveGebruiker(opgehaaldeGebruiker);
            }

            return LocalRedirect(ReturnUrl);
        }
    }
}

UI-MVC/Areas/Gebruikers/Pages/EditGebruiker.cshtml
@page
@using Microsoft.AspNetCore.Http.Extensions
@model UI_MVC.Areas.Gebruikers.Pages.EditGebruiker

@{
    ViewData["Title"] = "Wijzig Gebruiker";
    Layout = "_Layout";
}
@section Scripts
{
    <script type="module" src="~/dist/overview.entry.js" defer></script>
}
<link rel="stylesheet" href="~/dist/overview.css">

<h1 class="ha">@Model.Input.Voornaam @Model.Input.Achternaam Wijzigen</h1>
<div class="row">
    <div class="col-6">
        <div class="align-items-center">
            <form method="post">
                <div class="form-row">
                    <div class="form-group col-12">
                        <label asp-for="Input.Username"></label>
                        <input asp-for="Input.Username" class="form-control">
                        <span asp-validation-for="Input.Username" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-12">
                        <label asp-for="Input.Voornaam"></label>
                        <input asp-for="Input.Voornaam" class="form-control">
                        <span asp-validation-for="Input.Voornaam" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-12">
                        <label asp-for="Input.Achternaam"></label>
                        <input asp-for="Input.Achternaam" class="form-control">
                        <span asp-validation-for="Input.Achternaam" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-12">
                        <label asp-for="Input.Email"></label>
                        <input asp-for="Input.Email" class="form-control">
                        <span asp-validation-for="Input.Email" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-row">
                    <div class="form-group col-12">
                        <label asp-for="Input.School"></label>
                        <input asp-for="Input.School" class="form-control">
                        <span asp-validation-for="Input.School" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-row">
                    <button type="submit" class="btn btn-primary" style="margin: 10px" asp-page-handler="EditGebruiker" asp-route-id="@Model.Input.Id" asp-route-returnUrl="@Model.ReturnUrl">Wijzigen</button>
                    <a class="btn btn-danger" style="margin: 10px" asp-area="Gebruikers" asp-page="/SchoolGebruikers" asp-route-returnUrl="@Model.ReturnUrl" asp-route-schoolId="@Model.Input.SchoolId">Annuleren</a>
                </div>
            </form>
        </div>
    </div>
</div>

UI-MVC/Areas/Gebruikers/Pages/Gebruikers.cshtml
@page
@using Microsoft.AspNetCore.Http.Extensions
@model UI_MVC.Areas.Gebruikers.Pages.Gebruikers


@{
    Layout = "_Layout";
}

@section Scripts
{
    <script type="module" src="~/dist/overview.entry.js" defer></script>
}

<div class="row">
    <h1>Gebruikers</h1>
</div>
<div class="btn-group-justified">
    <a class="btn btn-primary" id="checkAlles">Select All</a>
    <a class="btn btn-primary" id="checkNiets">Deselect All</a>
</div>
<form method="post">
    <div class="row">
        <div class="col-8">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">Username</th>
                    <th scope="col">Voornaam</th>
                    <th scope="col">Achternaam</th>
                    <th scope="col">Email</th>
                    <th scope="col">School</th>
                    <th scope="col">Beheren</th>
                </tr>
                </thead>
                <tbody>

                @foreach (var g in @Model.Input.DetailsLeerkrachten)
                {
                    <tr>
                        <td>@g.Leerkracht.Username</td>
                        <td>@g.Leerkracht.Voornaam</td>
                        <td>@g.Leerkracht.Achternaam</td>
                        <td>@g.Leerkracht.Email</td>
                        <td>@g.Leerkracht.School.Naam</td>
                        <td>
                            <input type="checkbox" asp-for="@g.IsChecked" name="cb" value="@g.Leerkracht.Id"/>
                        </td>
                        <td>
                            <a class="btn btn-primary" asp-area="Gebruikers" asp-page="/EditGebruiker" asp-route-returnUrl="@Model.ReturnUrl" asp-route-id="@g.Leerkracht.Id">Beheren</a>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
        <div class="col-4">
            <div class="row">
                <input type="submit" class="btn btn-primary" value="Verwijderen" asp-page-handler="DeleteAsync"/>
            </div>
        </div>
    </div>
</form>

UI-MVC/Areas/Gebruikers/Pages/SchoolGebruikers.cshtml
@page
@model UI_MVC.Areas.Gebruikers.Pages.SchoolGebruikers


@{
    ViewData["Title"] = "Gebruikers" + @Model.Input.DetailsLeerkrachten[0].Leerkracht.School.Naam;
    Layout = "_Layout";
}
<link rel="stylesheet" href="~/dist/overview.css">

@section Scripts
{
    <script type="module" src="~/dist/overview.entry.js" defer></script>
}

<div class="jumbotron">
    <div class="row kaartTop my-3 p-3 bg-white rounded box-shadow verticalalign">
        <div class="col-10">
            <h1 class="ha">Gebruikers @Model.Input.DetailsLeerkrachten[0].Leerkracht.School.Naam</h1>
        </div>
    </div>
    
    <div class="btn-group-justified float-left">
        <button class="btn btn-primary" id="checkAlles">Select All</button>
        <button class="btn btn-primary" id="checkNiets">Deselect All</button>
    </div>
    
    <form method="post">
        <div class="row">
            <div class="col-12 float-right">
                <input type="submit" class="btn btn-danger float-right" value="Verwijderen" asp-page-handler="DeleteGebruiker" asp-route-returnUrl="@Model.ReturnUrl"/>
            </div>
        </div>
        
        @foreach (var g in Model.Input.DetailsLeerkrachten)
        {
            <div class="row my-3 p-3 bg-white rounded box-shadow verticalalign">
                <div class="col-1 text-center">
                    <label class="checkbox path">
                        <input type="checkbox" asp-for="@g.IsChecked" name="cb" value="@g.Leerkracht.Id">
                        <svg viewBox="0 0 21 21">
                            <path d="M5,10.75 L8.5,14.25 L19.4,2.3 C18.8333333,1.43333333 18.0333333,1 17,1 L4,1 C2.35,1 1,2.35 1,4 L1,17 C1,18.65 2.35,20 4,20 L17,20 C18.65,20 20,18.65 20,17 L20,7.99769186"></path>
                        </svg>
                    </label>
                </div>
                <div class="col-10">
                    <p class="pe"><strong class="d-block">@g.Leerkracht.Username</strong> @g.Leerkracht.Voornaam @g.Leerkracht.Achternaam </p>
                </div>
                <div class="col-1">
                    <a asp-area="Gebruikers" asp-page="/EditGebruiker" asp-route-returnUrl="@Model.ReturnUrl" asp-route-id="@g.Leerkracht.Id">
                        <svg height="50%" viewBox="0 0 16 16" fill="black" xmlns="http://www.w3.org/2000/svg">
                            <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z"/>
                        </svg>
                    </a>
                </div>
            </div>
        }
    </form>
    
</div>

@*****************************************@

@* <div class="row"> *@
@*      <h1>Gebruikers @Model.Input.DetailsLeerkrachten[0].Leerkracht.School.Naam</h1>  *@
@* </div> *@
@* <div class="btn-group-justified"> *@
@*     <a class="btn btn-primary" id="checkAlles">Select All</a> *@
@*     <a class="btn btn-primary" id="checkNiets">Deselect All</a> *@
@* </div> *@
@* <form method="post"> *@
@*     <div class="row"> *@
@*         <div class="col-8"> *@
@*             <table class="table"> *@
@*                 <thead> *@
@*                 <tr> *@
@*                     <th scope="col">Username</th> *@
@*                     <th scope="col">Voornaam</th> *@
@*                     <th scope="col">Achternaam</th> *@
@*                     <th scope="col">Email</th> *@
@*                     <th scope="col">Selecteren</th> *@
@*                     <th scope="col">Beheren</th> *@
@*                 </tr> *@
@*                 </thead> *@
@*                 <tbody> *@
@* *@
@*                 @foreach (var g in Model.Input.DetailsLeerkrachten) *@
@*                 { *@
@*                     <tr> *@
@*                         <td>@g.Leerkracht.Username</td> *@
@*                         <td>@g.Leerkracht.Voornaam</td> *@
@*                         <td>@g.Leerkracht.Achternaam</td> *@
@*                         <td>@g.Leerkracht.Email</td> *@
@*                         <td> *@
@*                             <input type="checkbox" asp-for="@g.IsChecked" name="cb" value="@g.Leerkracht.Id"/> *@
@*                         </td> *@
@*                         <td> *@
@*                             <a class="btn btn-primary" asp-area="Gebruikers" asp-page="/EditGebruiker" asp-route-returnUrl="@Model.ReturnUrl" asp-route-id="@g.Leerkracht.Id">Beheren </a> *@
@*                         </td> *@
@*                     </tr> *@
@*                 } *@
@*                 </tbody> *@
@*             </table> *@
@*         </div> *@
@*         <div class="col-5"> *@
@*             <div class="row"> *@
@*                 <input type="submit" class="btn btn-primary" value="Verwijderen" asp-page-handler="DeleteGebruiker" asp-route-returnUrl="@Model.ReturnUrl"/> *@
@*             </div> *@
@*         </div> *@
@*     </div> *@
@* </form> *@

UI-MVC/Areas/Gebruikers/Pages/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}