UI-MVC/Areas/Klassen/Pages/AddKlass.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using ST.BL.Domain.Identity;
using ST.BL.Domain.InternMediateClasses;
using ST.BL.Domain.Scholen;
using ST.BL.Domain.Users;
using ST.BL.Interfaces;


namespace UI_MVC.Areas.Klassen.Pages
{
    public class AddKlass : PageModel
    {
        private readonly IKlasManager _klasManager;
        private readonly IGebruikerManager _gebruikerManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<AddKlass> _logger;
        private readonly IGebruikerKlassenManager _gebruikerKlassenManager;

        public AddKlass(
            IKlasManager klasManager,
            IGebruikerManager gebruikerManager,
            UserManager<ApplicationUser> userManager,
            ILogger<AddKlass> logger,
            IGebruikerKlassenManager gebruikerKlassenManager
        )
        {
            _klasManager = klasManager;
            _gebruikerManager = gebruikerManager;
            _userManager = userManager;
            _logger = logger;
            _gebruikerKlassenManager = gebruikerKlassenManager;
        }

        [BindProperty] public AddKlassModel Input { get; set; }

        public class AddKlassModel
        {
            [Required] [Display(Name = "Name")] public string Name { get; set; }

            [Required]
            [Display(Name = "Amount of students")]
            public int StudentsCount { get; set; }

            [Required]
            [Display(Name = "School Year")]
            public int SchoolYear { get; set; }
        }

        public string StatusMessage { get; set; }

        [BindProperty] public Gebruiker Gebruiker { get; set; }
        public string ReturnUrl { get; set; }

        public async Task OnGet(string returnUrl = null) 
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;

            var user = await _userManager.GetUserAsync(User);
            Gebruiker = new Gebruiker();
            Gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);
        }

        public async Task<IActionResult> OnPostAddKlassAsync(string returnUrl)
        {
            var user = await _userManager.GetUserAsync(User);
            if (user == null)
            {
                return NotFound($"Unable to load user with ID '{_userManager.GetUserId(User)}'.");
            }

            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);

            var klas = ClassChecker(gebruiker);

            if (klas == null) return Page();

            var gebKlas = new GebruikerKlassen
                {klas = klas, Gebruiker = gebruiker, KlasId = klas.Id, GebruikerId = gebruiker.Id};
            _gebruikerKlassenManager.AddGebruikerKlassen(gebKlas);

            _logger.LogInformation($"Klas {klas.Naam} added.");

            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;

            return LocalRedirect(ReturnUrl);
        }

        private Klas ClassGenerator(Gebruiker gebruiker)
        {
            return new Klas
            {
                AantalLeerlingen = Input.StudentsCount,
                Naam = Input.Name,
                School = gebruiker.School,
                StudieJaar = Input.SchoolYear
            };
        }

        private Klas ClassChecker(Gebruiker gebruiker)
        {
            var existingClasses = _gebruikerKlassenManager
                .GetGebruikerKlassen()
                .Where(g => g.GebruikerId == gebruiker.Id)
                .ToList();

            var klas = ClassGenerator(gebruiker);
            var classExists = existingClasses.Any(k => k.klas.Equals(klas));

            if (!classExists) return klas;
            StatusMessage = $"You already have added this class";
            return null;
        }
    }
}

UI-MVC/Areas/Klassen/Pages/AdminClasses.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ST.BL.Domain.Identity;
using ST.BL.Domain.InternMediateClasses;
using ST.BL.Domain.Scholen;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Klassen.Pages
{
    public class AdminClasses : PageModel
    {
        private readonly IGebruikerKlassenManager _gebruikerKlassenManager;
        private readonly IGebruikerManager _gebruikerManager;
        private readonly ISchoolManager _schoolManager;
        private readonly UserManager<ApplicationUser> _userManager;
        public School School { get; set; }

        public AdminClasses(
            IGebruikerKlassenManager gebruikerKlassenManager,
            UserManager<ApplicationUser> userManager,
            IGebruikerManager gebruikerManager, 
            ISchoolManager schoolManager
        )
        {
            _gebruikerManager = gebruikerManager;
            _gebruikerKlassenManager = gebruikerKlassenManager;
            _userManager = userManager;
            _schoolManager = schoolManager;
        }

        public List<GebruikerKlassen> Classes { get; set; }
        public string ReturnUrl { get; set; }

        public async Task OnGet(string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;
            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);
            School = gebruiker.School;
            
            //adhv de school van de admin, alle klassen tonen die bij die bepaalde school horen
            Classes = new List<GebruikerKlassen>();
            var leerkrachten = _gebruikerManager.GetGebruikers().ToList();

            foreach (var leerkracht in leerkrachten)
            {
                foreach (var gebruikerKlas in leerkracht.GebruikerKlassen)
                {
                    if (gebruikerKlas.klas.School.Id.Equals(gebruiker.School.Id))
                    {
                        Classes.Add(gebruikerKlas);
                    }
                }
            }
        }

        public IActionResult OnPostDeleteAsync(int klasId, string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;

            var klas = _gebruikerKlassenManager
                .GetGebruikerKlassen()
                .Single(k => k.KlasId == klasId);

            if (klas != null) _gebruikerKlassenManager.RemoveGebruikerKlassen(klas);

            return LocalRedirect(ReturnUrl);
        }
    }
}

UI-MVC/Areas/Klassen/Pages/EditClass.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Linq;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Klassen.Pages
{
    public class EditClass : PageModel
    {
        private readonly IKlasManager _klasManager;
        private readonly ISchoolManager _schoolManager;
        [BindProperty] public InputModel Input { get; set; }
        public string ReturnUrl { get; set; }


        public EditClass(IKlasManager klasManager, ISchoolManager schoolManager)
        {
            _klasManager = klasManager;
            _schoolManager = schoolManager;
        }

        public class InputModel
        {
            public int Id { get; set; }

            [Required]
            [Display(Name = "KlasName")]
            public string Name { get; set; }

            [Required]
            [Display(Name = "Aantal Leerlingen")]
            public int AantalLeerlingen { get; set; }

            [Required]
            [Display(Name = "StudieJaar")]
            public int StudieJaar { get; set; }

            [Required] [Display(Name = "School")] public string School { get; set; }
            public int SchoolId { get; set; }
        }

        public void OnGet(int id, string returnUrl = null)
        {
            var gekozenKlas = _klasManager.GetKlasById(id);
            Input = new InputModel
            {
                Id = id,
                Name = gekozenKlas.Naam,
                AantalLeerlingen = gekozenKlas.AantalLeerlingen,
                StudieJaar = gekozenKlas.StudieJaar,
                School = gekozenKlas.School.Naam,
                SchoolId = gekozenKlas.School.Id
            };
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;
        }

        public IActionResult OnPostEditClass(int id, string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;

            var opgehaaldeKlas = _klasManager.GetKlasById(id);
            opgehaaldeKlas.Naam = Input.Name;
            opgehaaldeKlas.AantalLeerlingen = Input.AantalLeerlingen;
            opgehaaldeKlas.StudieJaar = Input.StudieJaar;
            opgehaaldeKlas.School = _schoolManager.GetScholen().Single(s => s.Naam.Equals(Input.School));
            _klasManager.ChangeKlas(opgehaaldeKlas);

            return LocalRedirect(ReturnUrl);
        }
    }
}

UI-MVC/Areas/Klassen/Pages/Klassen.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ST.BL.Domain.Identity;
using ST.BL.Domain.InternMediateClasses;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Klassen.Pages
{
    public class Klassen : PageModel
    {
        private readonly IGebruikerKlassenManager _gebruikerKlassenManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IGebruikerManager _gebruikerManager;

        public Klassen(
            IGebruikerKlassenManager gebruikerKlassenManager,
            UserManager<ApplicationUser> userManager,
            IGebruikerManager gebruikerManager
        )
        {
            _gebruikerKlassenManager = gebruikerKlassenManager;
            _userManager = userManager;
            _gebruikerManager = gebruikerManager;
        }

        public List<GebruikerKlassen> Classes { get; set; }
        public string ReturnUrl { get; set; }
        public async Task OnGet(string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }
            ReturnUrl = returnUrl;
            
            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);
            Classes = new List<GebruikerKlassen>();
            
            Classes = _gebruikerKlassenManager
                .GetGebruikerKlassen()
                .Where(g => g.GebruikerId == gebruiker.Id)
                .ToList();
        }

        public async Task<IActionResult> OnPostDeleteAsync(int klasId, string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }
            ReturnUrl = returnUrl; //* /Klassen/Klassen
            
            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);

            var klas = _gebruikerKlassenManager
                .GetGebruikerKlassen()
                .Where(g => g.GebruikerId == gebruiker.Id)
                .Single(k => k.KlasId == klasId);

            if (klas != null) _gebruikerKlassenManager.RemoveGebruikerKlassen(klas);

            return LocalRedirect(returnUrl);
        }
    }
}

UI-MVC/Areas/Klassen/Pages/SelectedClass.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using ST.BL.Domain;
using ST.BL.Domain.Identity;
using ST.BL.Domain.Scholen;
using ST.BL.Domain.Sessies;
using ST.BL.Domain.Spellen;
using ST.BL.Domain.Users;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Klassen.Pages
{
    public class SelectedClass : PageModel
    {
        private readonly IKlasManager _klasManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IGebruikerManager _gebruikerManager;
        private readonly ISessieManager _sessieManager;

        public SelectedClass(
            IKlasManager klasManager,
            UserManager<ApplicationUser> userManager,
            IGebruikerManager gebruikerManager,
            ISessieManager sessieManager
        )
        {
            _klasManager = klasManager;
            _userManager = userManager;
            _gebruikerManager = gebruikerManager;
            _sessieManager = sessieManager;
        }

        public Klas Klas { get; set; }
        [BindProperty] public List<Sessie> Sessies { get; set; }
        public string ReturnUrl { get; set; }

        public async Task OnGet(int klasId)
        {
            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);
            Klas = new Klas();
            Klas = _klasManager.GetKlasById(klasId);

            Sessies = new List<Sessie>();
            Sessies = _sessieManager
                .GetSessies()
                .Where(s => s.Klas.Id == klasId)
                .Where(s => s.Creator.Id == gebruiker.Id)
                .ToList();

            foreach (var sessie in Sessies)
            {
                sessie.UniqueCode = Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(sessie.UniqueCode));
            }
        }
    }
}

UI-MVC/Areas/Klassen/Pages/AddKlass.cshtml
@page
@using ST.BL.Interfaces
@using Microsoft.AspNetCore.Http.Extensions
@model UI_MVC.Areas.Klassen.Pages.AddKlass


@{
    Layout = "_Layout";
    var gebruiker = Model.Gebruiker;
    ViewData["Title"] = "Klas Aanmaken";
}
<link rel="stylesheet" href="~/dist/overview.css">
<h1>Nieuwe Klas aanmaken</h1>

<div class="row">
    <div class="col-3 align-self-center">
        <img src="/img/school.jpg" alt="foto school" style="width: 100%;"/>
    </div>
    <div class="col-9">
        <div class="d-flex align-items-center flex-column">
            <h3>@gebruiker.School.Naam</h3>
            <form method="post">
                <div class="form-group" style="width: 20rem">
                    <label asp-for="Input.Name"></label>
                    <input asp-for="Input.Name" class="form-control">
                    <span asp-validation-for="Input.Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Input.StudentsCount"></label>
                    <input asp-for="Input.StudentsCount" class="form-control">
                    <span asp-validation-for="Input.StudentsCount" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Input.SchoolYear"></label>
                    <input asp-for="Input.SchoolYear" class="form-control">
                    <span asp-validation-for="Input.SchoolYear" class="text-danger"></span>
                </div>
                <div class="d-flex flex-row">
                    @* BinnenKlass, heeft een return value nodig om naa vorig scherm te geraken. *@
                    <button type="submit" class="btn btn-primary" style="margin: 10px" asp-page-handler="AddKlass" asp-route-returnUrl="@Model.ReturnUrl">Save Changes</button>
                    @* Verwijziging naar vorige Page *@
                    <a class="btn btn-danger" style="margin: 10px" asp-page="/Klassen" asp-area="Klassen" asp-route-returnUrl="@Model.ReturnUrl">Cancel Changes</a>
                </div>
            </form>
        </div>
    </div>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial"/>
}

UI-MVC/Areas/Klassen/Pages/AdminClasses.cshtml
@page
@using Microsoft.AspNetCore.Http.Extensions
@inject UserManager<ApplicationUser> UserManager
@model UI_MVC.Areas.Klassen.Pages.AdminClasses

@{
    Layout = "_Layout";
    ViewData["Title"] = "Klassen";
    var classes = Model.Classes;
    var returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
    returnUrl = $"~/{returnUrl.Substring(23)}";
}

@if (!User.IsInRole("Admin"))
{
    
    <div class="row">
        <img src="/img/accessdenied.jpg" style="width: 25%" alt="No entrare!"/>
    </div>
    <div class="row">
        <p class="pe">Helaas, u heeft geen toegang tot deze pagina!</p>
    </div>
} else {
<h2>Klassen @Model.School.Naam</h2>

<div class="jumbotron">
    <div class="d-flex flex-row align-items-center justify-content-around flex-wrap">
        @foreach (var c in classes)
        {
            <div class="card" style="width: 14rem; margin: 10px">
                <img src="/img/klas.png" class="card-img-top" alt="foto klas">
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center" style="margin-bottom: 5px">@c.klas.Naam</h5>
                    <p class="card-text d-flex justify-content-around" style="margin-bottom: 5px">@c.klas.StudieJaar</p>
                    <div class="row">
                        <p class="col d-flex justify-content-start" style="margin-bottom: 5px">Testen:</p>
                        <p class="col d-flex justify-content-end">x</p>
                    </div>
                    <div class="row">
                        <p class="col d-flex justify-content-start" style="margin-bottom: 5px">Studenten:</p>
                        <p class="col d-flex justify-content-end">@c.klas.AantalLeerlingen</p>
                    </div>
                    <div class="row">
                        <form method="post" style="width: 90%">
                            @* Selecteer Klas en Ga naar ander Page => ReturnPage naar Deze Pagina *@
                            <a class="btn btn-primary col" style="margin: 0.5rem" asp-area="Klassen" asp-page="/SelectedClass" asp-route-klasId="@c.KlasId" asp-route-returnUrl="@returnUrl">Selecteren</a>
                            @* Delete de Gekozen klas en laat deze pagina weer zien - Omdat het een methode oproept, zal null => Deze pagina worden *@
                            <input type="submit" class="btn btn-danger col" style="margin: 0.5rem" value="Verwijderen" asp-page-handler="Delete" asp-route-klasId="@c.KlasId">
                        </form>
                    </div>
                </div>
            </div>
        }
        @* Creeer een nieuw klasse, na creatie Retourneer terug naar deze pagina *@
        <a class="card" style="width: 14rem; margin: 10px;text-decoration: none" type="submit" asp-area="Klassen" asp-page="/AddKlass" asp-route-returnUrl="@Model.ReturnUrl">
            <img src="https://via.placeholder.com/50" class="card-img-top" alt="..." style="height: 10rem;">
            <div class="card-body">
                <h5 class="card-title d-flex justify-content-center" style="margin-bottom: 5px">nieuweKlas</h5>
                <p class="d-flex justify-content-around" style="font-size: 9rem;margin: 0;">+</p>
            </div>
        </a>
    </div>
</div>
}

UI-MVC/Areas/Klassen/Pages/EditClass.cshtml
@page
@using Microsoft.AspNetCore.Http.Extensions
@using UI_MVC.Areas.Scholen.Pages
@model UI_MVC.Areas.Klassen.Pages.EditClass

@{
    ViewData["Title"] = "Wijzig klas";
    Layout = "_Layout";
}

<div class="row">
    <div class="d flex align-items-center">
        <h3>Klas Wijzigen</h3>
        <form method="post">
            <div class="form-group">
                <label asp-for="Input.Name"></label>
                <input asp-for="Input.Name">
                <span asp-validation-for="Input.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.AantalLeerlingen"></label>
                <input asp-for="Input.AantalLeerlingen">
                <span asp-validation-for="Input.AantalLeerlingen" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.StudieJaar"></label>
                <input asp-for="Input.StudieJaar">
                <span asp-validation-for="Input.StudieJaar" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Input.School"></label>
                <input asp-for="Input.School">
                <span asp-validation-for="Input.School" class="text-danger"></span>
            </div>
            <div class="d-flex flex-row">
                <button type="submit" class="btn btn-primary" style="margin: 10px" asp-page-handler="EditClass" asp-route-id="@Model.Input.Id" asp-route-returnUrl="@Model.ReturnUrl">Wijzigen</button>
                <a class="btn btn-danger" style="margin: 10px" asp-page="/AdminClasses" asp-area="Klassen" asp-route-returnUrl="@Model.ReturnUrl" asp-route-schoolId="@Model.Input.SchoolId">Annuleren</a>
            </div>
        </form>
    </div>
</div>

UI-MVC/Areas/Klassen/Pages/Klassen.cshtml
@page
@using ST.BL.Interfaces
@using Microsoft.AspNetCore.Http.Extensions
@model UI_MVC.Areas.Klassen.Pages.Klassen
@inject IGebruikerKlassenManager GebruikerKlassenManager
@inject IGebruikerManager GebruikerManager
@inject UserManager<ApplicationUser> UserManager


@{
    Layout = "_Layout";
    var classes = Model.Classes;

    var returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
    returnUrl = $"~/{returnUrl.Substring(23)}";
    ViewData["Title"] = "Mijn Klassen";

}
<br>
<h2>Mijn Klassen</h2>

<div class="jumbotron">
    <div class="d-flex flex-row align-items-center justify-content-around flex-wrap">
        @foreach (var c in classes)
        {
            <div class="card" style="width: 14rem; margin: 10px">
                <img src="/img/klas.png" class="card-img-top" alt="foto klas">
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center" style="margin-bottom: 5px">@c.klas.Naam</h5>
                    <p class="card-text d-flex justify-content-around" style="margin-bottom: 5px">@c.klas.StudieJaar</p>
                    <div class="row">
                        <p class="col d-flex justify-content-start" style="margin-bottom: 5px">Testen:</p>
                        @* TODO: Fix Count *@
                        <p class="col d-flex justify-content-end">x</p>
                    </div>
                    <div class="row">
                        <p class="col d-flex justify-content-start" style="margin-bottom: 5px">Studenten:</p>
                        <p class="col d-flex justify-content-end">@c.klas.AantalLeerlingen</p>
                    </div>
                    <div class="row">
                        <form method="post" style="width: 90%">
                            @* Selecteer Klas en Ga naar ander Page => ReturnPage naar Deze Pagina *@
                            <a class="btn btn-primary col" style="margin: 0.5rem" asp-area="Klassen" asp-page="/SelectedClass" asp-route-klasId="@c.KlasId" asp-route-returnUrl="@returnUrl">Selecteren</a>
                            @* Delete de Gekozen klas en laat deze pagina weer zien - Omdat het een methode oproept, zal null => Deze pagina worden *@
                            <input type="submit" class="btn btn-danger col" style="margin: 0.5rem" value="Verwijderen" asp-page-handler="Delete" asp-route-klasId="@c.KlasId">
                        </form>
                    </div>
                </div>
            </div>
        }
        @* Creeer een nieuw klasse, na creatie Retourneer terug naar deze pagina *@
        <a class="card" style="width: 14rem; margin: 10px;text-decoration: none" type="submit" asp-area="Klassen" asp-page="/AddKlass" asp-route-returnUrl="@returnUrl">
            <img src="/img/klas.png" class="card-img-top" alt="foto klas" >
            <div class="card-body">
                <h5 class="card-title d-flex justify-content-center" style="margin-bottom: 5px">nieuweKlas</h5>
                <p class="d-flex justify-content-around" style="font-size: 9rem;margin: 0;">+</p>
            </div>
        </a>
    </div>
</div>

UI-MVC/Areas/Klassen/Pages/SelectedClass.cshtml
@page
@using Microsoft.EntityFrameworkCore.Infrastructure
@using Microsoft.AspNetCore.Http.Extensions
@model UI_MVC.Areas.Klassen.Pages.SelectedClass

@{
    Layout = "_Layout";
    var klasId = Model.Klas.Id;

    var returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
    returnUrl = $"~/{returnUrl.Substring(23)}";
}
<br>
<h2 style="text-align: center">@Model.Klas.Naam</h2>
<form method="post">
    <div class="d-flex flex-column">
        <div class="d-flex flex-row">
            <div class="col-2">
                <h2>Sessies</h2>

            </div>
            <div class="col-10">
                <form>
                    <input id="Searchbar-Sessies-Table-Input" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" style="max-width: 20rem;float: right">
                </form>
            </div>
        </div>

        <div class="input-group flex-column col-12">
            <div class="table-responsive">
                <table class="table table-striped table-hover table-sm" id="Searchbar-Sessies-Table">
                    <thead class="thead-dark">
                    <tr style="text-align: center">
                        <th scope="col">Naam</th>
                        <th scope="col">UniqueCode</th>
                        <th scope="col">AantalDeelnemers</th>
                        <th scope="col">Status</th>
                        <th scope="col">Soort Spel</th>
                        <th scope="col">Select</th>
                    </tr>
                    </thead>
                    <tbody>
                    @if (Model.Sessies.Count == 0)
                    {
                        <tr style="text-align: center">
                            <th colspan="6">
                                <h3>Nothing to display</h3>
                            </th>
                        </tr>
                    }
                    @foreach (var sessie in Model.Sessies)
                    {
                        <tr style="text-align: center">
                            <th scope="row" style="text-align: left">@sessie.Name</th>
                            <td>@sessie.UniqueCode</td>
                            <td>@sessie.AantalDeelnemers</td>
                            <td>@sessie.Status</td>
                            <td>@sessie.Spel.GetType().ShortDisplayName().Substring(0, sessie.Spel.GetType().ShortDisplayName().Length - 5)</td>
                            <td>
                                @* Verwijziging naar een nieuwe Pagina. Return naar deze pagina nodig *@
                                @* TODO: Fix results page *@
                                <a class="btn btn-sm btn-primary" asp-area="Sessies" asp-page="/SessieInfo" asp-route-klasId="@klasId" asp-route-sessieId="@sessie.Id" asp-route-returnUrl="@returnUrl">Results</a>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
            <hr>
        </div>
    </div>
    <hr>
    @* Binnenklasse. Verwijzigt naar een ander klassen. Heeft geen waarde nodig null => zal redirect naar deze pagina maken *@
</form>
<div style="text-align: center">
    <a class="btn btn-primary col" style="margin: 0.5rem;max-width: 15rem;" asp-area="Sessies" asp-page="AddSessie" asp-route-klasId="@klasId" asp-route-returnUrl="@returnUrl">Create New Sessie</a>
</div>


@section Scripts
{
    <script type="module" src="~/dist/tableSearch.entry.js" defer></script>
}

UI-MVC/Areas/Klassen/Pages/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}