UI-MVC/Areas/Sessies/Pages/AddSessie.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.WebUtilities;
using Microsoft.Extensions.Logging;
using ST.BL.Domain;
using ST.BL.Domain.Identity;
using ST.BL.Domain.InternMediateClasses;
using ST.BL.Domain.Sessies;
using ST.BL.Domain.Spellen;
using ST.BL.Domain.Stellingen;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Sessies.Pages
{
    public class AddSessie : PageModel
    {
        private readonly IKlasManager _klasManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ISessieManager _sessieManager;
        private readonly ISpelManager _spelManager;
        private readonly ILogger<AddSessie> _logger;
        private readonly IGebruikerManager _gebruikerManager;
        private readonly IKlasSpellenManager _klasSpellenManager;

        public AddSessie(
            IKlasManager klasManager,
            UserManager<ApplicationUser> userManager,
            ISessieManager sessieManager,
            ISpelManager spelManager,
            ILogger<AddSessie> logger,
            IGebruikerManager gebruikerManager,
            IKlasSpellenManager klasSpellenManager
        )
        {
            _klasManager = klasManager;
            _userManager = userManager;
            _sessieManager = sessieManager;
            _spelManager = spelManager;
            _logger = logger;
            _gebruikerManager = gebruikerManager;
            _klasSpellenManager = klasSpellenManager;
        }

        public int KlasId { get; set; }
        [BindProperty] public Sessie Sessie { get; set; }
        [BindProperty] public int SelectedSoortSpel { get; set; }
        [BindProperty] public List<KlasSpellen> KSList { get; set; }
        [BindProperty] public int Selected { get; set; }
        public string ReturnUrl { get; set; }
        public int SpelId { get; set; }

        public async Task<IActionResult> OnGetAsync(int klasId, string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;

            KlasId = klasId;

            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);

            KSList = new List<KlasSpellen>();
            KSList = _klasSpellenManager
                .GetKlasSpellen()
                .Where(k => k.KlasId == klasId)
                .Where(k => k.Spel.Creator.Equals(gebruiker))
                .ToList();

            return Page();
        }

        // public IActionResult OnPostCreateSpel(int klasId, string returnUrl = null)
        // {
        //     return RedirectToPage("/AddSpel", new {area = "Spellen", klasId, returnUrl});
        // }

        private static string RandomString(int length)
        {
            var random = new Random();
            const string chars = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789";
            return new string(Enumerable.Repeat(chars, length)
                .Select(s => s[random.Next(s.Length)]).ToArray());
        }

        public IActionResult OnPostSelectedSpel(int klasId, int spelId, string returnUrl = null)
        {
            var klas = _klasManager.GetKlasById(klasId);

            var items = _klasSpellenManager.GetKlasSpellen().ToList();
            foreach (var item in items)
            {
                item.Selected = false;
            }

            _klasSpellenManager.ChangeKlasSpelRange(items);

            var ks = _klasSpellenManager.GetKlasSpellen()
                .Where(k => k.KlasId.Equals(klasId))
                .SingleOrDefault(k => k.SpelId == spelId);

            ks.Selected = true;
            _klasSpellenManager.ChangeKlasSpel(ks);

            return RedirectToPage();
        }

        public IActionResult OnPostDeleteSessie(int sessieId, string returnUrl = null)
        {
            var sessie = _sessieManager.GetSessieById(sessieId);
            _sessieManager.RemoveSessie(sessie);

            return LocalRedirect(returnUrl);
        }

        public async Task<IActionResult> OnPostStartSessie(int spelId,int klasId, string returnUrl = null)
        {
            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);

            
            var klas = _klasManager.GetKlasById(klasId);
            var date = $"{DateTime.Today.Day}/{DateTime.Today.Month}/{DateTime.Today.Year}";
            var spel = _spelManager.GetSpelById(spelId);
            
            var sessie = new Sessie
            {
                Name = $"[{date} - {spel.Name}] - {klas.Sessies.Count} - {klas.Naam}",
                Klas = klas,
                Creator = gebruiker,
                AantalDeelnemers = klas.AantalLeerlingen,
                Status = Status.Open,
                Spel = spel,
                UniqueCode = WebEncoders.Base64UrlEncode(Encoding.UTF8.GetBytes(RandomString(7)))
            };
            var sessieResult = _sessieManager.AddSessie(sessie);

            return RedirectToPage("/StartSessie",new {sessieId = sessieResult.Id});
        }
    }
}

UI-MVC/Areas/Sessies/Pages/SchoolSessies.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ST.BL.Domain.Identity;
using ST.BL.Domain.Sessies;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Sessies.Pages
{
    public class SchoolSessies : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ISessieManager _sessieManager;
        private readonly IGebruikerManager _gebruikerManager;

        public SchoolSessies(
            UserManager<ApplicationUser> userManager,
            ISessieManager sessieManager,
            IGebruikerManager gebruikerManager
        )
        {
            _userManager = userManager;
            _sessieManager = sessieManager;
            _gebruikerManager = gebruikerManager;
        }

        public List<Sessie> Sessions { get; set; }
        public string ReturnUrl { get; set; }


        public async Task OnGet(string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;

            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);
            Sessions = new List<Sessie>();

            Sessions = _sessieManager
                .GetSessies()
                .Where(s => s.Creator.School.Id == gebruiker.School.Id)
                .ToList();
        }


        public IActionResult OnPostDeleteSessie(int sessieId, string returnUrl)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;
            var sessie = _sessieManager.GetSessieById(sessieId);
            _sessieManager.RemoveSessie(sessie);

            return LocalRedirect(returnUrl);
        }
    }
}

UI-MVC/Areas/Sessies/Pages/SelectedSessie.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore.Internal;
using ST.BL.Domain.Antwoorden;
using ST.BL.Domain.InternMediateClasses;
using ST.BL.Domain.Partijen;
using ST.BL.Domain.Sessies;
using ST.BL.Domain.Stellingen;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Sessies.Pages
{
    public class SelectedSessie : PageModel
    {
        private readonly ISessieManager _sessieManager;
        private readonly IPartijManager _partijManager;
        private readonly ISpelManager _spelManager;
        private readonly IAntwoordenManager _antwoordenManager;
        private readonly ISpelStellingenManager _spelStellingenManager;

        public SelectedSessie(
            ISessieManager sessieManager,
            IPartijManager partijManager,
            ISpelManager spelManager,
            IAntwoordenManager antwoordenManager,
            ISpelStellingenManager spelStellingenManager
        )
        {
            _sessieManager = sessieManager;
            _partijManager = partijManager;
            _spelManager = spelManager;
            _antwoordenManager = antwoordenManager;
            _spelStellingenManager = spelStellingenManager;
            Sessie = new Sessie();
            PartijenList = new List<Partij>();
            Stellingen = new List<Stelling>();
        }

        public Sessie Sessie { get; set; }
        public List<Partij> PartijenList { get; set; }
        public List<Stelling> Stellingen { get; set; }

        public void OnGet(int sessieId, string returnUrl = null)
        {
            var random = new Random();
            Sessie = _sessieManager.GetSessieById(sessieId);
            PartijenList = _partijManager.GetPartijen().ToList();
            var spel = _spelManager.GetSpelById(Sessie.Spel.SpelId);
            foreach (var spelStelling in spel.SpelStellingen)
            {
                if (spelStelling.Stelling.UserAntwoordOpStelling.Any()) continue;
                
                for (var i = 0; i < 18; i++)
                {
                    var ant = RandomAntwoord(random.Next(100));
                    _antwoordenManager.AddAntwoord(ant);
                    
                    spelStelling.Stelling.UserAntwoordOpStelling.Add(ant);

                }
                _spelStellingenManager.ChangeSpelStelling(spelStelling);
            }

            foreach (var spelStelling in spel.SpelStellingen)
            {
                Stellingen.Add(spelStelling.Stelling);
            }
        }

        public UserAntwoordOpStelling RandomAntwoord(int kans)
        {
            if (kans > 53)
            {
                return new UserAntwoordOpStelling
                {
                    Antwoord = "eens"
                };
            }

            return new UserAntwoordOpStelling
            {
                Antwoord = "oneens"
            };
        }
    }
}

UI-MVC/Areas/Sessies/Pages/SessieInfo.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ST.BL.Domain.Antwoorden;
using ST.BL.Domain.Sessies;
using ST.BL.Domain.Stellingen;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Sessies.Pages
{
    public class SessieInfo : PageModel
    {
        [BindProperty] public int SessieId { get; set; }
        public int AantalDeelnemers { get; set; }
        public Sessie Sessie { get; set; }
        public List<UserAntwoordOpStelling> UserAntwoorden { get; set; }
        public List<StellingModel> StellingModels { get; set; }
        
        private readonly ISessieManager _sessieManager;
        private readonly IAntwoordenManager _antwoordenManager;
        private readonly IStellingManager _stellingManager;
        private readonly IAnoniemeGebruikerManager _anoniemeGebruikerManager;

        public SessieInfo(ISessieManager sessieManager, IAntwoordenManager antwoordenManager, IStellingManager stellingManager, IAnoniemeGebruikerManager anoniemeGebruikerManager)
        {
            _sessieManager = sessieManager;
            _antwoordenManager = antwoordenManager;
            _stellingManager = stellingManager;
            _anoniemeGebruikerManager = anoniemeGebruikerManager;
        }
        
        public class StellingModel
        {
            public Stelling Stelling { get; set; }
            public int AantalEens { get; set; }
            public int AantalOneens { get; set; }
        }
        
        public void OnGet(int sessieId)
        {
            SessieId = sessieId;
            Sessie = _sessieManager.GetSessieById(sessieId);
            UserAntwoorden = new List<UserAntwoordOpStelling>();
            StellingModels = new List<StellingModel>();
            
            //voor alle anons in de sessie alle antwoorden ophalen en in de UserAntwoorden steken
            var anons = _anoniemeGebruikerManager.GetAnoniemeGebruikers().Where(a => a.Sessie.Id.Equals(Sessie.Id)).ToList();
            AantalDeelnemers = anons.Count();
            
            var antwoorden = _antwoordenManager.GetUserAntwoorden();
            
            //voor elke antwoord checken of de anon in deze sessie voorkwam, zo ja toevoegen aan lijst
            foreach (var antwoord in antwoorden)
            {
                var a = (UserAntwoordOpStelling) antwoord;
                if (anons.Contains(a.AnoniemeGebruiker))
                {
                    UserAntwoorden.Add(a);
                }
            }

            foreach (var spelStelling in Sessie.Spel.SpelStellingen)
            {
                //van alle userantwoorden checken of ze eens of oneens hebben geantwoord
                var eens = 0;
                var oneens = 0;
                foreach (var antwoordOpStelling in UserAntwoorden.Where(u => u.StellingId.Equals(spelStelling.StellingId)))
                {
                    if (antwoordOpStelling.Antwoord.Equals("Eens"))
                    {
                        eens++;
                    } else if (antwoordOpStelling.Antwoord.Equals("Oneens"))
                    {
                        oneens++;
                    }
                }
                
                var stelling = new StellingModel()
                {
                    Stelling = spelStelling.Stelling,
                    AantalEens = eens,
                    AantalOneens = oneens
                };
                StellingModels.Add(stelling);
            }
        }
    }
}

UI-MVC/Areas/Sessies/Pages/Sessies.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http.Extensions;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ST.BL.Domain.Identity;
using ST.BL.Domain.Sessies;
using ST.BL.Domain.Users;
using ST.BL.Interfaces;

namespace UI_MVC.Areas.Sessies.Pages
{
    public class Sessies : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ISessieManager _sessieManager;
        private readonly IGebruikerManager _gebruikerManager;

        public Sessies(
            UserManager<ApplicationUser> userManager,
            ISessieManager sessieManager,
            IGebruikerManager gebruikerManager
        )
        {
            _userManager = userManager;
            _sessieManager = sessieManager;
            _gebruikerManager = gebruikerManager;
        }

        public List<Sessie> Sessions { get; set; }
        public string ReturnUrl { get; set; }


        public async Task OnGet(string returnUrl = null)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;

            var user = await _userManager.GetUserAsync(User);
            var gebruiker = _gebruikerManager.GetGebruikerByIdentity(user);
            Sessions = new List<Sessie>();

            Sessions = _sessieManager
                .GetSessies()
                .Where(s => s.Creator.Id == gebruiker.Id)
                .ToList();
        }


        public IActionResult OnPostDeleteSessie(int sessieId, string returnUrl)
        {
            if (returnUrl == null)
            {
                returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
                returnUrl = $"~/{returnUrl.Substring(23)}";
            }

            ReturnUrl = returnUrl;
            var sessie = _sessieManager.GetSessieById(sessieId);
            _sessieManager.RemoveSessie(sessie);

            return LocalRedirect(returnUrl);
        }
    }
}

UI-MVC/Areas/Sessies/Pages/AddSessie.cshtml
@page
@using Microsoft.EntityFrameworkCore.Infrastructure
@using Microsoft.AspNetCore.Http.Extensions
@model UI_MVC.Areas.Sessies.Pages.AddSessie

@{
    Layout = "_Layout";
    var klasId = Model.KlasId;

    var returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
    returnUrl = $"~/{returnUrl.Substring(23)}";
}

@* TODO: Add Search bar *@
<br>
<div class="d-flex flex-row justify-content-between align-items-center">
    <h2>Add Sessie</h2>
    <a class="btn btn-success" asp-area="Spellen" asp-page="AddSpel" asp-route-klasId="@klasId" asp-route-returnUrl="@returnUrl">Create Spel</a>
</div>

<div>
    <form method="post">
        <div class="jumbotron" style="padding: 1rem 2rem;">
            <form>
                <input id="Searchbar-AddSessie-Table-Input" class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" style="max-width: 20rem; margin-bottom: 0.5rem;">
            </form>
            <div class="table-responsive">
                <table class="table table-striped table-hover table-sm" style="text-align: center" id="Searchbar-AddSessie-Table">
                    <thead class="thead-dark">
                    <tr>
                        <th scope="col">Naam</th>
                        <th scope="col">Soort Spel</th>
                        <th scope="col">Options</th>
                        <th scope="col">Stellingen</th>
                        <th scope="col">Status</th>
                        <th scope="col">Select</th>
                    </tr>
                    </thead>
                    <tbody>
                    @* TODO: Add nothing to display message *@
                    @foreach (var ks in Model.KSList)
                    {
                        var spelnaam = ks.Spel.GetType().ShortDisplayName();
                        <tr>
                            <td scope="row"><b>@ks.Spel.Name</b></td>
                            <td>@spelnaam.Substring(0, spelnaam.Length - 5)</td>
                            @* TODO: Options in a dropdown view *@
                            <td>
                                <div>ColorScreen: @ks.Spel.options.ColorScreenPostAnswer</div>
                                <div>
                                    AllowArugment: @ks.Spel.options.AllowArgumentInput
                                </div>
                                <div>
                                    ExplainWord: @ks.Spel.options.ExplainDifficultWord
                                </div>
                                <div>
                                    Skip: @ks.Spel.options.Skip
                                </div>
                            </td>
                            @* TODO: Stellingen in a dropdown view *@
                            <td>
                                @foreach (var i in ks.Spel.SpelStellingen)
                                {
                                    var vraag = "";
                                    vraag = i.Stelling.Vraag.Length > 20 ? i.Stelling.Vraag.Substring(0, 20) : i.Stelling.Vraag;
                                    <div>
                                        @vraag...
                                    </div>
                                }
                            </td>
                            @* TODO: Status color change *@
                            <td>
                                @ks.Spel.Status
                            </td>
                            @* TODO: instead of Selected -> Start Sessie *@
                            <td>
                                <form method="post">
                                    <input style="margin-top: 25px" type="submit" class="btn btn-dark" value="Start Sessie" asp-page-handler="StartSessie" asp-route-klasId="@klasId" asp-route-spelId="@ks.SpelId"/>
                                </form>
                            </td>
                        </tr>
                    }
                    </tbody>
                </table>
            </div>
        </div>
    </form>
</div>

@section Scripts
{
        <script type="module" src="~/dist/tableSearch.entry.js" defer></script>
}

UI-MVC/Areas/Sessies/Pages/SchoolSessies.cshtml
@page
@using Microsoft.AspNetCore.Http.Extensions
@model UI_MVC.Areas.Sessies.Pages.SchoolSessies

@{
    Layout = "_Layout";
    var gebruikers = Model.Sessions;

    var returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
    returnUrl = $"~/{returnUrl.Substring(23)}";

}

@section Scripts
{
    <script type="module" src="~/dist/overview.entry.js" defer></script>
}

<div class="row">
    <h1>Sessies van @Model.Sessions[1].Creator.School.Naam</h1>
</div>
<div class="btn-group-justified">
    <a class="btn btn-primary" id="checkAlles">Select All</a>
    <a class="btn btn-primary" id="checkNiets">Deselect All</a>
</div>
<form method="post">
    <div class="row">
        <div class="col-8">
            <table class="table">
                <thead>
                <tr>
                    <th scope="col">SessieNaam</th>
                    <th scope="col">Klas</th>
                    <th scope="col">Status</th>
                    <th scope="col">AantalDeelnemers</th>

                    <th scope="col">Beheren</th>
                </tr>
                </thead>
                <tbody>

                @foreach (var g in @Model.Sessions)
                {
                    <tr>
                        <td>@g.Name</td>
                        <td>@g.Klas.Naam</td>
                        <td>@g.Status</td>
                        <td>
                            <input type="checkbox"/>
                        </td>
                    </tr>
                }
                </tbody>
            </table>
        </div>
        <div class="col-4">
            <div class="row">
                <input type="submit" class="btn btn-primary" value="Verwijderen" asp-page-handler="DeleteSessie" asp-route-returnUrl="@returnUrl"/>
            </div>
        </div>
    </div>
</form>

UI-MVC/Areas/Sessies/Pages/SelectedSessie.cshtml
@page
@model UI_MVC.Areas.Sessies.Pages.SelectedSessie
@using System.Web.Helpers

@{
    Layout = "_layout";
    var stellingen = Model.Stellingen;
    var sessie = Model.Sessie;
}
<br>
<h2>Resultaat {@sessie.Name}</h2>
<p>heeft Spel : @Model.Sessie.Spel.Name
<p>heeft Stellingen: @Model.Stellingen.Count</p>



@foreach (var stelling in stellingen)
{
    var partijantwoordenList = stelling.PartijAntwoordOpStelling.ToList();
    
    <h5>@stelling.StellingOnderwerp</h5>
    foreach (var partijAntwoord in partijantwoordenList)
    {
        var count = stelling.UserAntwoordOpStelling.Count(x => x.Antwoord.ToLower().Equals(partijAntwoord.Antwoord));
        var total = stelling.UserAntwoordOpStelling.Count;
        var percent = ((decimal)count / total).ToString("0.00%");
        <p>[@partijAntwoord.Partij.Naam] had als antwoord (@partijAntwoord.Antwoord), {@percent} had dezelfde antwoord gegeven in deze klas</p>
        <p>@count / @total</p>
    }
}

UI-MVC/Areas/Sessies/Pages/SessieInfo.cshtml
@page
@using UI_MVC.Areas.Sessies.Pages
@model UI_MVC.Areas.Sessies.Pages.SessieInfo

@{
    Layout = "_Layout";
    ViewData["Title"] = "Sessie "+@Model.Sessie.Id;
}
<input hidden type="text" asp-for="@Model.SessieId" value="@Model.SessieId">
<h2>@Model.Sessie.Name</h2>
<p>Created by: <b>@Model.Sessie.Creator.Voornaam @Model.Sessie.Creator.Achternaam</b></p>
<p><b>@Model.AantalDeelnemers</b> deelnemer(s)</p>
<p><b>@Model.UserAntwoorden.Count</b> antwoorden ingegeven</p>
@* <p>Type spel: <b>@Model.Sessie.Spel.GetType().Name</b></p> *@

<h2>Stellingen</h2>
<table class="table">
    @foreach (SessieInfo.StellingModel stelling in @Model.StellingModels)
    {
        <tr>
            <td>@stelling.Stelling.Vraag</td>
            <td><b>@stelling.AantalEens</b> eens</td>
            <td><b>@stelling.AantalOneens</b> oneens</td>
        </tr>
    }
</table>

UI-MVC/Areas/Sessies/Pages/Sessies.cshtml
@page
@using Microsoft.AspNetCore.Http.Extensions
@model UI_MVC.Areas.Sessies.Pages.Sessies

@{
    Layout = "_Layout";
    var sessies = Model.Sessions;
    var returnUrl = Url.Content(HttpContext.Request.GetEncodedUrl());
    returnUrl = $"~/{returnUrl.Substring(23)}";
}
<br>
<h2>Mijn Sessies</h2>

<div class="jumbotron">
    <div class="d-flex flex-row align-items-center justify-content-around flex-wrap">
        @foreach (var sessie in sessies)
        {
            <div class="card" style="width: 14rem; margin: 10px">
                <img src="https://via.placeholder.com/50" class="card-img-top" alt="..." style="height: 10rem;">
                <div class="card-body">
                    <h5 class="card-title d-flex justify-content-center" style="margin-bottom: 5px">@sessie.Name</h5>
                    <p class="card-text d-flex justify-content-around" style="margin-bottom: 5px">@sessie.Klas.Naam</p>
                    <div class="row">
                        <p class="col d-flex justify-content-start" style="margin-bottom: 5px">Status:</p>
                        <p class="col d-flex justify-content-end">@sessie.Status</p>
                    </div>
                    <div class="row">
                        <p class="col d-flex justify-content-start" style="margin-bottom: 5px">Studenten:</p>
                        <p class="col d-flex justify-content-end">@sessie.AantalDeelnemers</p>
                    </div>
                    <div class="row">
                        <form method="post" style="width: 90%">
                            <a class="btn btn-primary col" style="margin: 0.5rem" asp-area="Sessies" asp-page="/SelectedSessie" asp-route-sessieId="@sessie.Id" asp-route-returnUrl="@Request.GetEncodedUrl()">Bekijk Resultaten</a>
                            <input type="submit" class="btn btn-danger col" style="margin: 0.5rem" value="Verwijderen" asp-page-handler="DeleteSessie" asp-page="AddSessie" asp-route-sessieId="@sessie.Id" asp-route-returnUrl="@returnUrl">
                        </form>
                    </div>
                </div>
            </div>
        }
    </div>
</div>

UI-MVC/Areas/Sessies/Pages/StartSessie.cshtml
@page
@using Microsoft.AspNetCore.WebUtilities
@using System.Text
@model UI_MVC.Areas.Sessies.Pages.StartSessie

@{
    Layout = "_Layout";
}
<input hidden type="text" asp-for="@Model.SessieId" value="@Model.SessieId">
<label hidden id="sessieId">@Model.SessieId</label>
<label hidden id="cookie">@Model.CookieVal</label>


<h2 class="text-center">Sessie ID: @Model.SessieId</h2>
<div class="jumbotron d-flex flex-column">
    <div class="row">
        <div class="col-6 d-flex flex-row justify-content-around align-items-center">
            <h2 style="border: 1px solid #000;padding: 1rem;">CODE: @Encoding.UTF8.GetString(WebEncoders.Base64UrlDecode(Model.Sessie.UniqueCode))</h2>
        </div>
        <div class="col-6 d-flex flex-row justify-content-around" style="border-left:1px solid #000;height:10rem">
            <img src="@Model.QrImage" alt="" style="height: 150px;width: 150px">
        </div>
    </div>
    <br>
    <div class=" d-flex flex-row align-self-center">
        <h3>
            <span id="studentCount"></span> Student(en) Connected
        </h3>
    </div>

</div>
@if (User.Identity.IsAuthenticated)
{
@*     <button class="btn btn-danger" id="resetUsers">RESET USERS</button> *@
    <label hidden id="location">@Model.Location</label>
    <label hidden id="locationTeacher">@Model.LocationTeacher</label>
    <div class="d-flex flex-row justify-content-center">
        <input type="button" class="btn btn-primary" id="startSpel" value="Start Spel" style="min-width: 15rem;"/>
    </div>
}

@section Scripts
{
    <script type="module" src="~/dist/tryout.entry.js" defer></script>
}

UI-MVC/Areas/Sessies/Pages/_StatusMessage.cshtml
@model string

@if (!String.IsNullOrEmpty(Model))
{
    var statusMessageClass = Model.StartsWith("Error") ? "danger" : "success";
    <div class="alert alert-@statusMessageClass alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        @Model
    </div>
}